<?php
$languages_list = [
    'ar_SA' => ['name' => 'العربية', 'native_name' => 'Arabic'],
    'bg_BG' => ['name' => 'български', 'native_name' => 'Bulgarian'],
    'cs_CZ' => ['name' => 'Čeština', 'native_name' => 'Czech'],
    'da_DK' => ['name' => 'Dansk', 'native_name' => 'Danish'],
    'de_DE' => ['name' => 'Deutsch', 'native_name' => 'German'],
    'el_GR' => ['name' => 'Ελληνικά', 'native_name' => 'Greek'],
    'en_GB' => ['name' => 'British English', 'native_name' => 'English'],
    'en_US' => ['name' => 'American English', 'native_name' => 'English'],
    'es_ES' => ['name' => 'Español', 'native_name' => 'Spanish'],
    'et_EE' => ['name' => 'Eesti Keel', 'native_name' => 'Estonian'],
    'fa_IR' => ['name' => 'فارسی', 'native_name' => 'Persian'],
    'fi_FI' => ['name' => 'Suomen Kieli', 'native_name' => 'Finnish'],
    'fil_PH' => ['name' => 'Filipino', 'native_name' => 'Filipino'],
    'fr_FR' => ['name' => 'Français', 'native_name' => 'French'],
    'he_IL' => ['name' => 'עִברִית', 'native_name' => 'Hebrew'],
    'hi_IN' => ['name' => 'हिंदी', 'native_name' => 'Hindi'],
    'hu_HU' => ['name' => 'Magyar', 'native_name' => 'Hungarian'],
    'id_ID' => ['name' => 'Bahasa Indonesia', 'native_name' => 'Indonesian'],
    'it_IT' => ['name' => 'Italiano', 'native_name' => 'Italian'],
    'lt_LT' => ['name' => 'Lietuvių', 'native_name' => 'Lithuanian'],
    'lv_LV' => ['name' => 'Latviski', 'native_name' => 'Latvian'],
    'ja_JP' => ['name' => '日本語', 'native_name' => 'Japanese'],
    'km_KH' => ['name' => 'ខ្មែរ', 'native_name' => 'Khmer'],
    'ko_KR' => ['name' => '한국어', 'native_name' => 'Korean'],
    'nb_NO' => ['name' => 'Norsk', 'native_name' => 'Norwegian'],
    'nl_NL' => ['name' => 'Nederlands', 'native_name' => 'Dutch'],
    'pl_PL' => ['name' => 'Polski', 'native_name' => 'Polish'],
    'pt_BR' => ['name' => 'Português Brasileiro', 'native_name' => 'Portuguese Brazilian'],
    'pt_PT' => ['name' => 'Português Europeu', 'native_name' => 'Portuguese European'],
    'ro_RO' => ['name' => 'Română', 'native_name' => 'Romanian'],
    'ru_RU' => ['name' => 'Русский', 'native_name' => 'Russian'],
    'rw_RW' => ['name' => 'Kinyarwanda', 'native_name' => 'Kinyarwanda'],
    'sk_SK' => ['name' => 'Slovenský', 'native_name' => 'Slovak'],
    'sl_SI' => ['name' => 'Slovenski', 'native_name' => 'Slovenian'],
    'sv_SE' => ['name' => 'Svenska', 'native_name' => 'Swedish'],
    'tg_TJ' => ['name' => 'Тоҷикӣ', 'native_name' => 'Tajik'],
    'th_TH' => ['name' => 'ไทย', 'native_name' => 'Thai'],
    'tr_TR' => ['name' => 'Türkçe', 'native_name' => 'Turkish'],
    'uk_UA' => ['name' => 'Yкраїнська', 'native_name' => 'Ukrainian'],
    'vi_VN' => ['name' => 'Tiếng Việt', 'native_name' => 'Vietnamese'],
    'zh_CN' => ['name' => '简体中文', 'native_name' => 'Chinese Simplified'],
    'zh_HK' => ['name' => '繁體中文（香港）', 'native_name' => 'Chinese Traditional'],
    'zh_TW' => ['name' => '繁體中文（台灣）', 'native_name' => 'Chinese Traditional'],
];